######################################################################
# Automatically generated by qmake (2.01a) Tue May 12 19:26:45 2009
######################################################################

TEMPLATE = app
TARGET = cattmul
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glwidget.h window.h ui_MainWindow.h foundation.h \
    Bezier.h
FORMS += MainWindow.ui
SOURCES += glwidget.cpp main.cpp window.cpp
QT += opengl
